apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: MyApp
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: MyApp
    spec:
      containers:
      - name: venkat
        image: maddulavenkat1/flask-app:flaskversion2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service1
    #  labels:
    #    app.kubernetes.io/name: MyApp
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
